import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import React from "react";
import { ClerkProvider } from "@clerk/nextjs";
import {TopNav} from "~/app/_components/topnav";

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by me",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="flex-col gap-4">
          <div className="w-full">First layout</div>
        <TopNav />
        {children}</body>
      </html>
    </ClerkProvider>
  );
}
